name: deploy

on: 
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    

    steps:
    - name: Step-1 Checkout-respository to ubuntu runner
      uses: actions/checkout@v3

    - name: Step-2 install Nodes.js
      uses: actions/setup-node@v3
      with:
          node-version: 18.16.0

    - name: Step-3 Install dependencies
      run: npm install

    - name: Build Website
      run: npm run build

    - name: Set AWS Credential
      uses: aws-actions/configure-aws-credentials@v2
      with: 
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
    - name: Copy to S3
      run: aws s3 sync ./build/ s3://landingtemplate


